const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

const ensurePdfDir = () => {
  const baseDir = path.resolve(process.env.UPLOAD_DIR || 'uploads');
  const pdfDir = path.join(baseDir, 'agreements');
  if (!fs.existsSync(pdfDir)) {
    fs.mkdirSync(pdfDir, { recursive: true });
  }
  return pdfDir;
};

const generateAgreementPdf = async (agreement) => {
  const pdfDir = ensurePdfDir();
  const fileName = `agreement_${agreement.agreement_id}.pdf`;
  const filePath = path.join(pdfDir, fileName);

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);

    doc.pipe(stream);

    doc.fontSize(20).text('Beaver Rental Agreement', { align: 'center' });
    doc.moveDown();

    doc.fontSize(12).text(`Agreement ID: ${agreement.agreement_id}`);
    doc.text(`Status: ${agreement.status}`);
    doc.text(`Property: ${agreement.property?.name || 'N/A'}`);
    doc.text(`Owner: ${agreement.owner?.full_name || 'N/A'} (${agreement.owner?.email || 'N/A'})`);
    doc.text(`Tenant: ${agreement.tenant?.full_name || 'N/A'} (${agreement.tenant?.email || 'N/A'})`);
    doc.moveDown();

    doc.text(`Address: ${agreement.property?.address_line || 'N/A'}, ${agreement.property?.city || ''}, ${agreement.property?.state || ''} - ${agreement.property?.pincode || ''}`);
    doc.moveDown();

    doc.text(`Start Date: ${agreement.start_date}`);
    doc.text(`End Date: ${agreement.end_date}`);
    doc.text(`Monthly Rent: INR ${agreement.rent_amount}`);
    doc.text(`Deposit: INR ${agreement.deposit_amount}`);
    doc.text(`GST Rate: ${agreement.gst_rate || 0}%`);
    doc.text(`Rent Due Day: ${agreement.rent_due_day}`);
    doc.moveDown();

    doc.fontSize(14).text('Terms', { underline: true });
    doc.moveDown(0.5);

    const terms = agreement.terms || {};
    const termEntries = Object.entries(terms);
    if (termEntries.length === 0) {
      doc.fontSize(12).text('Standard Beaver rental terms apply.');
    } else {
      termEntries.forEach(([key, value]) => {
        doc.fontSize(12).text(`${key}: ${typeof value === 'object' ? JSON.stringify(value) : value}`);
      });
    }

    doc.moveDown();
    doc.text('This document is generated by Beaver for rental record and agreement reference purposes.');

    doc.end();

    stream.on('finish', resolve);
    stream.on('error', reject);
  });

  return {
    filePath,
    fileName,
    relativePath: path.join('agreements', fileName).replace(/\\/g, '/')
  };
};

module.exports = {
  generateAgreementPdf
};
